"""v2

Revision ID: 2ad52ab9ab59
Revises: 39a188e47b32
Create Date: 2024-07-03 17:53:22.963070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad52ab9ab59'
down_revision: Union[str, None] = '39a188e47b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('sexo', sa.String(length=2), nullable=False))
    op.drop_column('atletas', 'sexto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('sexto', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_column('atletas', 'sexo')
    # ### end Alembic commands ###
